name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java environments
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build QQTangExtractor
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar
      - name: Publish Jar
        uses: actions/upload-artifact@v3
        with:
          name: resource-extrcator.jar
          path: build/libs/resource-extractor.jar
  QQTang52_Beta1Build1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Java environments
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get Extractor
        uses: actions/download-artifact@v3
        with:
          name: resource-extrcator.jar
      - name: Get Installer
        run: |
          wget "https://github.com/QQTangMemorialUnofficial/installation-packages/releases/download/5.2_Beta1Build1/QQTang5.2_Beta1Build1.EXE"
      - name: Extract Installer
        run: |
          7z x QQTang5.2_Beta1Build1.EXE -oextracted -aoa
      - name: Extract Resources
        run: |
          java -jar resource-extractor.jar QQTang5.2_Beta1Build1 ./extracted
          zip -r QQTang5.2_Beta1Build1 QQTang5.2_Beta1Build1
      - name: Publish Resources
        uses: actions/upload-artifact@v3
        with:
          name: QQTang5.2_Beta1Build1
          path: QQTang5.2_Beta1Build1
